### ISSUE TITLE
v4.4.2

### ISSUE THREAD

**Issue by renau** [ICE-V-Wireless/ICE-V-Wireless#13]
The version used for IDF v4.4.2 does not seem to support macos ARM IDF v5.2 works fine with ESP32 (I tried with other boards).

The issue is that some of the firmware code is not correct for IDF 5.2. Any plan to migrate?

**Comment by gojimmypi** [comment]
I see [IDF 5.2](https://github.com/espressif/esp-idf/tags) is still only development. I'm curious as to exactly which errors you are seeing with that version. I know the migration from 4.x to 5.x can be bumpy. Can you post some examples? thanks.

**Comment by renau** [comment]
This is what I get when I try to compile the IDF-4.4.2 (I do not get any error with IDF 5.2)

```                                                                                                                                                                                                      ./install.sh
Detecting the Python interpreter
Checking "python" ...
/Users/renau/cse121/esp-idf-v4.4.2/tools/detect_python.sh: line 16: python: command not found
Checking "python3" ...
Python 3.11.3
"python3" has been detected
Installing ESP-IDF tools
Current system platform: macos-arm64
Traceback (most recent call last):
  File "/Users/renau/cse121/esp-idf-v4.4.2/tools/idf_tools.py", line 1860, in <module>
    main(sys.argv[1:])
  File "/Users/renau/cse121/esp-idf-v4.4.2/tools/idf_tools.py", line 1856, in main
    action_func(args)
  File "/Users/renau/cse121/esp-idf-v4.4.2/tools/idf_tools.py", line 1423, in action_install
    targets = clean_targets(args.targets)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/renau/cse121/esp-idf-v4.4.2/tools/idf_tools.py", line 1085, in clean_targets
    export_targets_to_idf_env_json(targets_from_tools_json)
  File "/Users/renau/cse121/esp-idf-v4.4.2/tools/idf_tools.py", line 1053, in export_targets_to_idf_env_json
    targets = list(set(targets + get_user_defined_targets()))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/renau/cse121/esp-idf-v4.4.2/tools/idf_tools.py", line 1099, in get_user_defined_targets
    if env == idf_env_json['idfSelectedId']:
              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'idfSelectedId'
```
